### ISSUE TITLE
Hello,I want ask that what is the 'data_file' in function build_data(data_file, data_list) ?

### ISSUE THREAD

**Issue by Keeplingshi** [anoperson/jointEE-NN#1]
I have the ACE corpus, but I don't know what get stored in data_file .

**Comment by Keeplingshi** [comment]
I have the ACE corpus, but I don't know what get stored in data_file .

**Comment by pegahsafaie** [comment]
Hi Chen, Can you please tell me how did you access ACE dataset? as Ive seen in website it is not free. is there any free version of the dataset?

**Comment by Alivewwt** [comment]
what should the data form be ?can I run the code ?

**Comment by xiaoya6666** [comment]
I have the same problem with you , and can you tell me what is the 'data_file' if you have solved it?

**Comment by anoperson** [comment]
Sorry for the late response. I added a sample file in "data".
